import mongoose from 'mongoose'

/**
 * Signal
 *
 * Represents an intelligence alert generated by the Pulse signal engine.
 * Signals are produced automatically by scanning church data for anomalies —
 * vacant pastoral charges, membership decline, missing submissions, etc.
 *
 * Every signal is scoped to a conference and a church.
 * The tier determines urgency: FLASH → PRIORITY → ROUTINE.
 *
 * Signals remain open (resolvedAt: null) until an admin resolves them.
 * Resolved signals are retained for historical analysis.
 *
 * dedupKey prevents the engine from creating duplicate signals for the same
 * ongoing condition (e.g. a church that has been vacant for 90 days shouldn't
 * produce a new signal every time the job runs).
 */

export const SIGNAL_TIERS   = ['FLASH', 'PRIORITY', 'ROUTINE']
export const SIGNAL_SOURCES = ['engine', 'manual']

export const SIGNAL_TYPES = [
  // Staffing
  'vacant_church',
  'vacant_church_long',     // vacant > 90 days
  'delegation_expiry',      // elder delegation expiring within 30 days
  'tenure_milestone',       // pastor at 5/7/10yr milestone
  'tenure_long',            // pastor > 10yr at same church
  // Membership
  'membership_decline',     // YoY > 10%
  'membership_decline_severe', // YoY > 25%
  'membership_growth',      // YoY > 15% (positive flag)
  'membership_stagnant',    // < 2% change over 5yr
  // Data quality
  'stats_overdue_1q',
  'stats_overdue_2q',
  'stats_overdue_4q',
  'tithe_missing',
  // Financial
  'tithe_decline',          // YoY > 10%
  'tithe_growth',           // YoY > 10% (positive flag)
  'tithe_anomaly',          // ratio outlier (> 2σ from conference avg)
]

const signalSchema = new mongoose.Schema({

  // Territory scoping — always set, never trusted from request
  conferenceCode: { type: String, required: true, uppercase: true, trim: true, index: true },
  churchCode:     { type: String, required: true, uppercase: true, trim: true, index: true },

  // Classification
  tier:       { type: String, enum: SIGNAL_TIERS,   required: true },
  signalType: { type: String, enum: SIGNAL_TYPES,   required: true },
  signal:     { type: String, required: true, trim: true, maxlength: 200 }, // short label
  detail:     { type: String, required: true, trim: true, maxlength: 1000 }, // full sentence

  // Raw data that triggered this signal — flexible shape per type
  data: { type: mongoose.Schema.Types.Mixed, default: null },

  // How this signal was created
  source: { type: String, enum: SIGNAL_SOURCES, default: 'engine' },

  // Lifecycle
  generatedAt: { type: Date, default: Date.now },
  resolvedAt:  { type: Date, default: null },
  resolvedBy:  { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  resolutionNote: { type: String, default: null, maxlength: 500 },

  // Dedup key — unique per ongoing condition, prevents duplicate signals.
  // Format: '<signalType>:<churchCode>'  e.g. 'vacant_church:SNSW-QUEAN'
  // When the condition clears, the engine auto-resolves and the key is freed.
  dedupKey: { type: String, required: true, trim: true },

}, { timestamps: true })

// --- Indexes ---

// Primary query: Intel Feed for a conference (active signals by tier)
signalSchema.index({ conferenceCode: 1, tier: 1, resolvedAt: 1 })

// Per-church signal history
signalSchema.index({ churchCode: 1, resolvedAt: 1 })

// Dedup enforcement — one active signal per condition
// Partial index: only enforce uniqueness among unresolved signals
signalSchema.index(
  { dedupKey: 1, resolvedAt: 1 },
  { unique: true, partialFilterExpression: { resolvedAt: null } }
)

export const Signal = mongoose.model('Signal', signalSchema)
